import Head from 'next/head'
import React, {useEffect, useState} from "react";
import Image from 'next/image'
import styles from "../styles/Home.module.css"
import {useRouter} from "next/router";
import ImageFeedComponent from "../components/image/imageFeed.cmp";
import { imageServices } from "../services";


export default function Home() {
  
  const router = useRouter();
  // const [componentDidMount, setComponentDidMount] = useState<boolean>(false);
  const [data, setData] = useState([]);
  const [dataError, setDataError] = useState([]);


  // useEffect(() => {
  //   setComponentDidMount(true);
  // }, []);

  useEffect(() => {
      if (true) {
          imageServices.getImageFeed({router})
              .then(res => {
                  if (!res.error) {
                      console.log(res)
                      setData(res.data);
                  } else setDataError(res);
              });
      }
  }, []);


  return (
    <div className={styles.container}>
      <Head>
        <title>Flickr Image Feed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <div className="container">
          <h2>Flicr Image Gallery</h2>
          <div className="row">
            {
              data.map((imageFeed, idx) => (
                <ImageFeedComponent key={idx} data={imageFeed}/>
              ))
            }
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          by{' Muhammad Akbar Syahwana '}
          {/* <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
        </a>
      </footer>
    </div>
  )
}
